server:
  port: 8081
---


spring:
  h2:
    console:
      enabled: true
      path: /console
---
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:rdb
    username: sa
    password:  
  profiles: qa
 
---
server:
  port: 8081
  
---
spring:
  profiles:
    active: dev 
    